utils: U is not a valid option for open anymore
Has been deprecated for some time (so we got a warning), on recent
version of python3 it doesn't even recognized.

    f = open(filename, 'rbU')
        ^^^^^^^^^^^^^^^^^^^^^
    ValueError: invalid mode: 'rbU'